version: "3"
services:
  jupyter:
    container_name: jupyter
    build:
      context: jupyter
    env_file:
      - .env
    ports:
      - 8888:8888
    volumes:
      - ./jupyter:/code
      - ./data:/mnt/data

  postgres:
    container_name: postgres
    build:
      context: postgres
    volumes:
      - ./postgres/postgressql-data:/var/lib/postgresql/data
      - ./data:/mnt/data
    env_file:
      - .env
    ports:
      - 5432:5432

  simple_http:
    container_name: simple_http
    build:
      context: simple_http
    volumes:
      - ./data:/mnt/data
    env_file:
      - .env
    ports:
      - 80:80

  lambda_node:
    container_name: lambda_node
    build:
      context: lambda_node
    env_file:
      - .env
    ports:
      - 3000:3000
    network_mode: host
